LineLength:
  Max: 99

AllCops:
  TargetRubyVersion: 2.5

Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
