language: ruby
rvm:
  - ruby-head
  - 2.5.1
  - 2.4.1
  - 2.3.4
  - 2.2.7
before_install: gem install bundler -v 1.11.2
after_success:
- >
  [ "${TRAVIS_PULL_REQUEST}" != "false" ] &&
  [ "${TRAVIS_RUBY_VERSION}" = "2.5.1" ] &&
    PRONTO_PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} \
      bundle exec pronto run -f github_status github_pr -c origin/${TRAVIS_BRANCH}
